export const itemTypes = [
    'Ammunition',
    'Battleaxe',
    'Blowgun',
    'Chakram',
    'Club',
    'Dagger',
    'Dart',
    'Fist weapon',
    'Flail',
    'Glaive',
    'Greataxe',
    'Greatclub',
    'Greatsword',
    'Halberd',
    'Hand Crossbow',
    'Handaxe',
    'Heavy Armor (Chain Mail)',
    'Heavy Armor (Plate)',
    'Heavy Armor (Ring Mail)',
    'Heavy Armor (Splint)',
    'Heavy Crossbow',
    'Instrument',
    'Javelin',
    'Lance',
    'Light Armor (Leather)',
    'Light Armor (Padded)',
    'Light Armor (Studded Leather)',
    'Light Crossbow',
    'Light Hammer',
    'Longbow',
    'Longsword',
    'Mace',
    'Martial Melee Weapon',
    'Martial Ranged Weapon',
    'Maul',
    'Medium Armor (Breastplate)',
    'Medium Armor (Chain Shirt)',
    'Medium Armor (Half Plate)',
    'Medium Armor (Hide)',
    'Medium Armor (Scale Mail)',
    'Morningstar',
    'Musical Instrument',
    'Musket',
    'Net',
    'Pike',
    'Pistol',
    'Quarterstaff',
    'Rapier',
    'Revolver',
    'Rod',
    'Scimitar',
    'Scythe',
    'Shield',
    'Shortbow',
    'Shortsword',
    'Sickle',
    'Simple Melee Weapon',
    'Simple Ranged Weapon',
    'Sling',
    'Spear',
    'Staff',
    'Trident',
    'Wand',
    'War Pick',
    'Warhammer',
    'Whip',
    'Wondrous Item',
    'Wondrous Item (Body)',
    'Wondrous Item (Cloak)',
    'Wondrous Item (Feet)',
    'Wondrous Item (Hands)',
    'Wondrous Item (Head)',
    'Wondrous Item (Jewelry)',
] as const;

export const rarities = ['Common', 'Uncommon', 'Rare', 'Very Rare', 'Legendary', 'Artifact'] as const;
