export const itemTypes = [
    { label: 'Ammunition', value: 'Ammunition' },
    { label: 'Battleaxe', value: 'Battleaxe' },
    { label: 'Blowgun', value: 'Blowgun' },
    { label: 'Chakram', value: 'Chakram' },
    { label: 'Club', value: 'Club' },
    { label: 'Dagger', value: 'Dagger' },
    { label: 'Dart', value: 'Dart' },
    { label: 'Fist weapon', value: 'Fist weapon' },
    { label: 'Flail', value: 'Flail' },
    { label: 'Glaive', value: 'Glaive' },
    { label: 'Greataxe', value: 'Greataxe' },
    { label: 'Greatclub', value: 'Greatclub' },
    { label: 'Greatsword', value: 'Greatsword' },
    { label: 'Halberd', value: 'Halberd' },
    { label: 'Hand Crossbow', value: 'Hand Crossbow' },
    { label: 'Handaxe', value: 'Handaxe' },
    { label: 'Heavy Armor (Chain Mail)', value: 'Heavy Armor (Chain Mail)' },
    { label: 'Heavy Armor (Plate)', value: 'Heavy Armor (Plate)' },
    { label: 'Heavy Armor (Ring Mail)', value: 'Heavy Armor (Ring Mail)' },
    { label: 'Heavy Armor (Splint)', value: 'Heavy Armor (Splint)' },
    { label: 'Heavy Crossbow', value: 'Heavy Crossbow' },
    { label: 'Instrument', value: 'Instrument' },
    { label: 'Javelin', value: 'Javelin' },
    { label: 'Lance', value: 'Lance' },
    { label: 'Light Armor (Leather)', value: 'Light Armor (Leather)' },
    { label: 'Light Armor (Padded)', value: 'Light Armor (Padded)' },
    { label: 'Light Armor (Studded Leather)', value: 'Light Armor (Studded Leather)' },
    { label: 'Light Crossbow', value: 'Light Crossbow' },
    { label: 'Light Hammer', value: 'Light Hammer' },
    { label: 'Longbow', value: 'Longbow' },
    { label: 'Longsword', value: 'Longsword' },
    { label: 'Mace', value: 'Mace' },
    { label: 'Martial Melee Weapon', value: 'Martial Melee Weapon' },
    { label: 'Martial Ranged Weapon', value: 'Martial Ranged Weapon' },
    { label: 'Maul', value: 'Maul' },
    { label: 'Medium Armor (Breastplate)', value: 'Medium Armor (Breastplate)' },
    { label: 'Medium Armor (Chain Shirt)', value: 'Medium Armor (Chain Shirt)' },
    { label: 'Medium Armor (Half Plate)', value: 'Medium Armor (Half Plate)' },
    { label: 'Medium Armor (Hide)', value: 'Medium Armor (Hide)' },
    { label: 'Medium Armor (Scale Mail)', value: 'Medium Armor (Scale Mail)' },
    { label: 'Morningstar', value: 'Morningstar' },
    { label: 'Musical Instrument', value: 'Musical Instrument' },
    { label: 'Musket', value: 'Musket' },
    { label: 'Net', value: 'Net' },
    { label: 'Pike', value: 'Pike' },
    { label: 'Pistol', value: 'Pistol' },
    { label: 'Quarterstaff', value: 'Quarterstaff' },
    { label: 'Rapier', value: 'Rapier' },
    { label: 'Revolver', value: 'Revolver' },
    { label: 'Rod', value: 'Rod' },
    { label: 'Scimitar', value: 'Scimitar' },
    { label: 'Scythe', value: 'Scythe' },
    { label: 'Shield', value: 'Shield' },
    { label: 'Shortbow', value: 'Shortbow' },
    { label: 'Shortsword', value: 'Shortsword' },
    { label: 'Sickle', value: 'Sickle' },
    { label: 'Simple Melee Weapon', value: 'Simple Melee Weapon' },
    { label: 'Simple Ranged Weapon', value: 'Simple Ranged Weapon' },
    { label: 'Sling', value: 'Sling' },
    { label: 'Spear', value: 'Spear' },
    { label: 'Staff', value: 'Staff' },
    { label: 'Trident', value: 'Trident' },
    { label: 'Wand', value: 'Wand' },
    { label: 'War Pick', value: 'War Pick' },
    { label: 'Warhammer', value: 'Warhammer' },
    { label: 'Whip', value: 'Whip' },
    { label: 'Wondrous Item', value: 'Wondrous Item' },
    { label: 'Wondrous Item (Body)', value: 'Wondrous Item (Body)' },
    { label: 'Wondrous Item (Cloak)', value: 'Wondrous Item (Cloak)' },
    { label: 'Wondrous Item (Feet)', value: 'Wondrous Item (Feet)' },
    { label: 'Wondrous Item (Hands)', value: 'Wondrous Item (Hands)' },
    { label: 'Wondrous Item (Head)', value: 'Wondrous Item (Head)' },
    { label: 'Wondrous Item (Jewelry)', value: 'Wondrous Item (Jewelry)' },
];

export const rarities = [
    { label: 'Common', value: 'Common' },
    { label: 'Uncommon', value: 'Uncommon' },
    { label: 'Rare', value: 'Rare' },
    { label: 'Very Rare', value: 'Very Rare' },
    { label: 'Legendary', value: 'Legendary' },
    { label: 'Artifact', value: 'Artifact' },
];
